### ISSUE TITLE
Update translation to 0.5.0

### ISSUE THREAD

**Issue by gonzalocasas** [XinArkh/roslibpy-docs-zh#1]
We published an updated version of `roslibpy` and it would be fantastic if you could update the documentation accordingly. The changes are here: https://github.com/gramaziokohler/roslibpy/compare/v0.4.1...v0.6.0

**Comment by XinArkh** [comment]
Got that! Being busy with my graduation project these days, so I may put it off a little. But I will let you know once I finish it.

**Comment by gonzalocasas** [comment]
👍

**Comment by XinArkh** [comment]
@gonzalocasas v0.6.0 doc has been updated. Please have a check!

**Comment by gonzalocasas** [comment]
@XinArkh fantastic! thanks a lot!
